module.exports = Object.freeze({
  SOURCE_TYPES: ["**/*.html", "**/*.js", "**/*.css"],

  IMAGE_TYPES: [
    "**/*.apng",
    "**/*.bmp",
    "**/*.gif",
    "**/*.ico",
    "**/*.cur",
    "**/*.jpg",
    "**/*.jpeg",
    "**/*.jfif",
    "**/*.pjpeg",
    "**/*.pjp",
    "**/*.png",
    "**/*.svg",
    "**/*.tif",
    "**/*.tiff",
    "**/*.webp",
    "**/*.heic",
    "**/*.heif",
  ],

  AUDIO_TYPES: [
    "**/*.3gp",
    "**/*.aac",
    "**/*.flac",
    "**/*.mpg",
    "**/*.mpeg",
    "**/*.mp3",
    "**/*.m4a",
    "**/*.m4v",
    "**/*.m4p",
    "**/*.oga",
    "**/*.ogg",
    "**/*.ogv",
    "**/*.mov",
    "**/*.wav",
    "**/*.webm",
    "**/*.aiff",
    "**/*.wma",
  ],

  VIDEO_TYPES: ["**/*.mov", "**/*.mp4", "**/*.avi", "**/*.mkv", "**/*.wmv"],

  DATA_TYPES: [
    "**/*.json",
    "**/*.csv",
    "**/*.tsv",
    "**/*.txt",
    "**/*.xml",
    "**/*.yaml",
    "**/*.yml",
    "**/*.xls",
    "**/*.xlsx",
    "**/*.sql",
    "**/*.ini",
    "**/*.md",
    "**/*.rdf",
    "**/*.h5",
  ],
});
