module.exports = Object.freeze({
  SOURCE_TYPES: ["**/*.html", "**/*.js", "**/*.css"],

  IMAGE_TYPES: [
    "**/*.apng",
    "**/*.bmp",
    "**/*.gif",
    "**/*.ico",
    "**/*.cur",
    "**/*.jpg",
    "**/*.jpeg",
    "**/*.jfif",
    "**/*.pjpeg",
    "**/*.pjp",
    "**/*.png",
    "**/*.svg",
    "**/*.tif",
    "**/*.tiff",
    "**/*.webp",
  ],

  AUDIO_TYPES: [
    "**/*.3gp",
    "**/*.aac",
    "**/*.flac",
    "**/*.mpg",
    "**/*.mpeg",
    "**/*.mpg",
    "**/*.mpeg",
    "**/*.mp3",
    "**/*.m4a",
    "**/*.m4v",
    "**/*.m4p",
    "**/*.oga",
    "**/*.ogg",
    "**/*.ogv",
    "**/*.ogg",
    "**/*.mov",
    "**/*.wav",
    "**/*.webm",
    "**/*.webm",
  ],

  VIDEO_TYPES: ["**/*.mov", "**/*.mp4"],
});
